language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - memcached
  - redis-server

install:
  - "pip install webtest coverage nose-cov flake8 python-coveralls"
  - "pip install -e ."

before_script: "flake8"

script:  "nosetests"

after_success:
  - coveralls
